dist: xenial
language: csharp
env:
  global:
    - Configuration=Release
    - ASPNETCORE_ENVIRONMENT=Staging
services:
  - docker
  - rabbitmq
mono: none
dotnet: 3.1.100
branches:
  only:
  - master
  - /^release\/.*$/
  - develop
addons:
  apt:
    update: true
    packages:
    - rabbitmq-server
script:
 - set -e
 - docker pull microsoft/mssql-server-linux:2017-latest
 - docker run -p 1433:1433 -e 'SA_PASSWORD=Password12!' -e 'ACCEPT_EULA=Y' -e 'MSSQL_PID=Developer' -d microsoft/mssql-server-linux:2017-latest
 - sleep 180
 - cd build
 - export PATH="$PATH:/home/travis/.dotnet/tools"
 - ./build.sh